# Generated by Django 5.0.6 on 2024-07-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('Ene-Abr', 'enero - abri'), ('May-Ago', 'mayo - agosto'), ('Sep-Dic', 'septiembre - diciembre')], max_length=10, verbose_name='Periodo')),
                ('year', models.IntegerField(default=2024, verbose_name='Año')),
                ('cicle', models.CharField(default='2023 - 2024', max_length=10, verbose_name='Ciclo')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=2, verbose_name='Cuatrimestre')),
                ('semester_name', models.CharField(max_length=10, verbose_name='Cuatrimestre en letra')),
            ],
            options={
                'verbose_name': 'Cuatrimestre',
                'verbose_name_plural': 'Cuatrimestres',
                'ordering': ['id'],
            },
        ),
    ]
