# Generated by Django 5.0.6 on 2024-07-12 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careers',
            name='director',
        ),
        migrations.RemoveField(
            model_name='careers',
            name='plan',
        ),
        migrations.AddField(
            model_name='careers',
            name='year_plan',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='level',
            field=models.CharField(choices=[('TSU', 'Tecnico Superior Universitario'), ('Ing', 'Ingenieria'), ('Lic', 'Licenciatura'), ('M', 'Maestria')], max_length=20),
        ),
        migrations.AlterField(
            model_name='careers',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='careers',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('total_horas', models.IntegerField()),
                ('weekly_hours', models.IntegerField()),
                ('file', models.CharField(max_length=100)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.careers')),
            ],
        ),
    ]
