# Generated by Django 5.0.6 on 2024-07-15 18:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_career_subject_delete_careers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='semanal_hours',
            new_name='weekly_hours',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='practical_hours',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teorical_hours',
        ),
        migrations.AlterField(
            model_name='subject',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Hoja de Asignatura'),
        ),
    ]
