# Generated by Django 5.0.6 on 2024-07-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_remove_careers_director_remove_careers_plan_and_more'),
        ('careers', '0003_rename_semanal_hours_subject_weekly_hours_and_more'),
    ]

    operations = [
    ]
